apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-node-selector
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-node-selector
  template:
    metadata:
      labels:
        app: nginx-node-selector
    spec:
      nodeSelector:
        type: node-selector
      containers:
      - name: nginx
        image: nginx:1.12
        ports:
        - containerPort: 80

