apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-node-affinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-node-affinity
  template:
    metadata:
      labels:
        app: nginx-node-affinity
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: type
                operator: In
                values:
                - node-affinity
      containers:
      - name: nginx
        image: nginx:1.12
        ports:
        - containerPort: 80

